name: CI

on: 
  push:
    branches: 
      - master
    paths:
      - 'api/**'
  pull_request:
    branches: 
      - master
    paths:
      - 'api/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo hello, new api
