name: release

on: 
  release:

jobs:
  upload:
    name: Upload go build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go
      
      - name: build
        run: |
          go build .
          ls
          mkdir tmp
          cp ga tmp
          
      - name: list
        run: ls .
          
      - name: publish
        uses: skx/github-action-publish-binaries@release-0.11
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'ga'
      
      - name: publish_1
        uses: skx/github-action-publish-binaries@release-0.11
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'tmp/ga'
